version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smartassessdb
      POSTGRES_USER: smartassessuser
      POSTGRES_PASSWORD: smartassesspassword

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A smartassess worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command: celery -A smartassess beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
