from datetime import date, datetime
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework import status
from .models import Homework, Student
from .serializers import HomeworkSerializer, StudentSerializer, HomeworkStatusSerializer, FileUploadSerializer
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from openai import OpenAI
import fitz  # PyMuPDF
import json
from django.conf import settings


class HomeworkUploadView(APIView):
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        # Retrieve 'student_id' from the query parameters
        student_id = request.query_params.get('student_id')
        if not Student.objects.filter(id=student_id).exists():
            return Response({"error": "Student not found"}, status=status.HTTP_404_NOT_FOUND)
        homework = Homework.objects.filter(student_id=student_id).order_by('-submission_date').first()
        # Add default values for 'description' and 'title' if they are not provided
        # request.data['submission_date'] = date.today().isoformat()  # Add today's date as submission date
        # request.data.setdefault('description', 'Default Homework Description')
        # request.data.setdefault('title', 'Default Homework Title')
        # request.data['student'] = student_id
        #
        # # Proceed with serializing the homework data
        # serializer = HomeworkSerializer(data=request.data)
        # if serializer.is_valid():
        #     # Save the validated homework data
        #     homework = serializer.save()
        #     homework.grade_assignment()
        #     return Response(serializer.data, status=status.HTTP_201_CREATED)
        # else:
        #     # Return errors if the data is not valid
        #     return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        for key, value in request.data.items():
            if hasattr(homework, key):
                setattr(homework, key, value)

            # Always update submission date to today's date
        homework.submission_date = datetime.now()

        # Save the updated homework
        homework.save()

        # Optionally, regrade the assignment
        homework.grade_assignment()

        # Serialize the homework for the response
        serializer = HomeworkSerializer(homework)
        return Response(serializer.data, status=status.HTTP_200_OK)

class HomeworkListView(APIView):
    def get(self, request):
        homeworks = Homework.objects.all()
        serializer = HomeworkSerializer(homeworks, many=True)
        return Response(serializer.data)


class HomeworkStatusView(APIView):
    def get(self, request):
        # homeworks = Homework.objects.all()
        homeworks = Homework.objects.order_by('student', '-submission_date').distinct('student')
        serializer = HomeworkStatusSerializer(homeworks, many=True)
        return Response(serializer.data)

class HomeworkDetailView(APIView):
    def get(self, request):
        student_id = request.query_params.get('student_id')
        homework = Homework.objects.filter(student_id=student_id).order_by('-submission_date').first()
        serializer = HomeworkSerializer(homework)
        return Response(serializer.data)

class FileUploadView(APIView):
    parser_classes = [MultiPartParser, FormParser]

    def post(self, request, *args, **kwargs):
        serializer = FileUploadSerializer(data=request.data)
        if serializer.is_valid():
            file = serializer.validated_data['file']
            fs = FileSystemStorage(location='professor/')  # Define the directory to save files
            filename = fs.save(file.name, file)
            file_url = fs.url(filename)
            return Response({'file_url': file_url}, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

def extract_text_from_pdf(pdf_path):
    """Extracts text from a PDF file."""
    doc = fitz.open(pdf_path)
    text = ""
    for page in doc:
        text += page.get_text()
    doc.close()
    return text

def get_answers_from_chatgpt(questions):
    """Sends questions to ChatGPT and returns the generated answers."""
    client = OpenAI(api_key=settings.OPENAI_API_KEY)
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "system", "content": "You are a tutor."}, {"role": "user", "content": questions}]
    )
    return response.choices[0].message.content

def grade_with_openai_model(chatgpt_answers, professor_solution, rubric):
    """Uses OpenAI's model to compare student answers and professor solution for grading."""
    prompt = f"""
    Given the OpenAI's answer (generated by GPT):
    {chatgpt_answers}

    And the professor's solution:
    {professor_solution}

    With this grading rubric:
    {rubric}

    Evaluate and provide a grade and feedback. Keep is short and clear.
    """
    client = OpenAI(api_key=settings.OPENAI_API_KEY)
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

class AutomatedGradingView(APIView):
    def get(self, request):
        questions = extract_text_from_pdf('professor/Question.pdf')
        professor_solution = extract_text_from_pdf('professor/Solution.pdf')
        rubric = extract_text_from_pdf('professor/Rubric.pdf')

        chatgpt_answers = get_answers_from_chatgpt(questions)
        grading_results = grade_with_openai_model(chatgpt_answers, professor_solution, rubric)

        return Response({"result": grading_results})