# Generated by Django 4.2.12 on 2024-05-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='submission_date',
            field=models.DateTimeField(),
        ),
    ]
